/**
 * Name: Calculator
 * Author:Manish
 */
/**
 * Version      Date           Name              Description
 * ======================================================================
 * v0.1         14-09          Manish            Added add method
 * ======================================================================
 */
public with sharing class Calculator {
    public Calculator() {

    }
    public integer add(integer a, Integer b){
        return a+b;
    }
    
}
